---
### ------------------------------------------------------------
### deploy変数
### ------------------------------------------------------------
deploy_user: "ubuntu"
deploy_group: "ubuntu"

### zsh
zsh_etc_dir: "/etc/mkt/zsh"
zsh_users:
  - root
  - ubuntu
zsh_ps_host_color: "yellow"
