---
# [目的]
#   ubuntuにパッケージを色々入れる
# [条件]
#   ubuntu-22.04.1

- hosts: ubuntu
  become: yes
  gather_facts: False

  tasks:
    - name: Update system repositories
      raw:  apt update && apt upgrade -y

    - name: Install essential packages
      raw:  apt install apt-transport-https ca-certificates curl software-properties-common -y

    - name: Install useful packages
      raw:  apt install tig jq lv make net-tools tree moreutils -y

    - name: Remove noisy old apps
      raw:  apt remove ed nano -y
