---
# [目的]
#   ubuntuにdocker周りを入れる (OpenStack版)
# [条件]
#   Ubuntu16.04

- hosts: ubuntu
  serial: 1                     # エラーは致命的なので1台ずつ
  become: yes
  gather_facts: False

  tasks:
    ######################################################################
    ### Docker
    
    # キーの追加 [冪等]
    - name: add key via proxy
      raw: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
      # raw: apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

    # repository追加
    - name: add docker official repository
      raw: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      #raw: echo "deb https://apt.dockerproject.org/repo ubuntu-xenial main" > /etc/apt/sources.list.d/docker.list

    # storage-driverとproxyの設定 (systemdのoverride)
    #
    # /etc/systemd/system/docker.service.d/override.conf:
    # ----------------------------------------------------------------------
    # [Service]
    # ExecStart=
    # ExecStart=/usr/bin/dockerd -H fd:// -s overlay2 --bip=172.16.0.1/24 --fixed-cidr=172.16.128.128/24
    # Environment='HTTP_PROXY=http://172.16.128.1:8080'
    # ----------------------------------------------------------------------
    - name: create docker setting directory
      raw: mkdir -p /etc/systemd/system/docker.service.d/

    - name: put docker setting into override.conf
      raw: echo "[Service]\nExecStart=\nExecStart=/usr/bin/dockerd -H fd:// -s overlay2 --bip=172.16.0.1/24 --fixed-cidr=172.16.128.128/24\n"> /etc/systemd/system/docker.service.d/override.conf

    - name: update package for docker
      raw: apt-get update

    - name: install docker
      raw: apt-get install docker-ce -y

    - name: restart systemd docker
      raw: systemctl daemon-reload && systemctl restart docker

    - name: add user to docker group
      raw: usermod -aG docker ubuntu

    - name: install docker-compose
      raw: "[ ! -x /usr/local/bin/docker-compose ] && curl -L https://github.com/docker/compose/releases/download/1.15.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose || true"

