---
# [目的]
#   ubuntuに日本語設定を入れる
# [条件]
#   Ubuntu16.04

- hosts: ubuntu
  become: yes
  gather_facts: False

  tasks:
    # TIMEZONEをJSTにする
    - name: timedatectl set-timezone Asia/Tokyo
      raw:  timedatectl set-timezone Asia/Tokyo

    - name: locale-gen ja_JP.UTF-8
      raw:  locale-gen ja_JP.UTF-8
