---
# [目的]
#   ubuntuにmotdを入れる
# [条件]
#   Ubuntu18.04

- hosts: ubuntu
  become: yes
  gather_facts: False

  tasks:
    - name: disable all
      shell: chmod -x /etc/update-motd.d/*

    - name: show information of package and reboot
      shell: chmod +x /etc/update-motd.d/90-updates-available /etc/update-motd.d/98-reboot-required

    - name: apt install dbar
      apt:
        name: dbar
        state: present

    - name: put 50-df
      copy:
        src: motd/50-df
        dest: /etc/update-motd.d/50-df
        mode: 0755
