---
# [目的]
#   ubuntuにmotdを入れる
# [条件]
#   ubuntu-22.04.1

- hosts: ubuntu
  become: yes
  gather_facts: False

  tasks:
    - name: apt install dbar
      apt: name=dbar state=present

    - name: disable all
      shell: chmod -x /etc/update-motd.d/*

    - name: enable 90-updates-available
      shell: chmod +x /etc/update-motd.d/90-updates-available

    - name: put /etc/update-motd.d/*
      copy: src="{{item}}" dest="/etc/update-motd.d/{{item | basename}}" mode=0755
      with_fileglob:
        - "motd/*"
