---
# [目的]
#   ubuntuにzshを入れる
# [条件]
#   ubuntu-22.04.1

- hosts: ubuntu
  become: yes
  gather_facts: False

  tasks:
    # updateはしない（リストを更新されたくない）
    - name: zshをインストール
      apt:
        name: zsh
        state: present
    - name: rcファイルをコピー({{deploy_user}})
      template:
        src: .zshrc.j2
        dest: "/home/{{deploy_user}}/.zshrc"
        owner: "{{deploy_user}}"
        group: "{{deploy_user}}"
        mode: 0644
    - name: rcファイルをコピー(root)
      template:
        src: .zshrc.j2
        dest: "/root/.zshrc"
        mode: 0644
    - name: chsh({{deploy_user}})
      raw: chsh -s /bin/zsh {{deploy_user}}
