---
# [目的]
#   ubuntuにzshを入れる
# [条件]
#   ubuntu-22.04.1

- hosts: ubuntu
  become: yes
  gather_facts: False

  tasks:
    # updateはしない（リストを更新されたくない）
    - name: zshをインストール
      apt:
        name: zsh
        state: present
    - name: rcファイルをコピー({{deploy_user}})
      copy:
        src: .zshrc
        dest: "/home/{{deploy_user}}/.zshrc"
        mode: 0644
    - name: rcファイルをコピー(root)
      copy:
        src: .zshrc
        dest: "/root/.zshrc"
        mode: 0644
